.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -43,8 +43,8 @@ jobs:
         run: |
           latest_version="$(jq -r '.version' package.json)"
           count_expected=9
-          count_actual="$(grep -c "setup-pixi@$latest_version" README.md)"
+          count_actual="$(grep -c "setup-pixi@v$latest_version" README.md || true)"
           if [ "$count_actual" -ne "$count_expected" ]; then
-            echo "::error file=README.md::Expected $count_expected mentions of setup-pixi@$latest_version in README.md, but found $count_actual."
+            echo "::error file=README.md::Expected $count_expected mentions of setup-pixi@v$latest_version in README.md, but found $count_actual."
             exit 1
           fi
