Add test for latest version in README

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -32,3 +32,19 @@ jobs:
       
       - name: Lint
         run: pnpm lint
+
+  reference-latest-version-in-readme:
+    name: Reference latest version in README
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Assert latest setup-pixi version is mentioned in README
+        run: |
+          latest_version="$(jq -r '.version' package.json)"
+          count_expected=9
+          count_actual="$(grep -c "setup-pixi@$latest_version" README.md)"
+          if [ "$count_actual" -ne "$count_expected" ]; then
+            echo "::error file=README.md::Expected $count_expected mentions of setup-pixi@$latest_version in README.md, but found $count_actual."
+            exit 1
+          fi
