.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -211,6 +211,7 @@ jobs:
       - name: Move pixi.toml
         run: mv test/default/* .
       - uses: lisanna-dettwyler/action-post-run@d053b9b43d788b87a409f6cdb3b6fc87c6c8a4fe
+        if: matrix.os != 'windows-latest'
         with:
           run: |
             set -euxo pipefail
@@ -218,13 +219,22 @@ jobs:
             ${{ matrix.post-cleanup == 'true' && '! ' || '' }}test -d ~/.rattler
             ${{ matrix.post-cleanup == 'true' && '! ' || '' }}test -d ~/.cache/rattler
             ${{ matrix.post-cleanup == 'true' && '! ' || '' }}test -f ~/.pixi/bin/pixi
+      - run: |
+          mkdir -p ~/.rattler
+        if: matrix.os != 'windows-latest'
+        # ~/.rattler is only created if the user has logged in and os is linux
+      - uses: lisanna-dettwyler/action-post-run@d053b9b43d788b87a409f6cdb3b6fc87c6c8a4fe
+        if: matrix.os == 'windows-latest'
+        with:
+          run: |
+            set -euxo pipefail
+            ${{ matrix.post-cleanup == 'true' && '! ' || '' }}test -d .pixi
+            ${{ matrix.post-cleanup == 'true' && '! ' || '' }}test -d "$TEMP/rattler"
+            ${{ matrix.post-cleanup == 'true' && '! ' || '' }}test -f ~/.pixi/bin/pixi
       - uses: ./
         with:
           post-cleanup: ${{ matrix.post-cleanup }}
-      - run: |
-          mkdir -p ~/.rattler
-        # ~/.rattler is only created if the user has logged in and os is linux
-        shell: bash
+
     
   no-lockfile:
     strategy:
@@ -254,73 +264,73 @@ jobs:
           pixi run python --version | grep -q 3.11
           pixi run test | grep -q "Hello world"
 
-  test-cache1:
-    name: Test cache 1/2
-    timeout-minutes: 10
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [windows-latest, ubuntu-latest, macos-latest]
-    steps:
-      - uses: actions/checkout@v4
-      - name: Move pixi files
-        run: mv test/default/* .
-      - uses: ./
-        with:
-          cache: true
-          cache-key: test-cache-${{ github.sha }}-${{ github.run_attempt }}-
-      # check the action logs to see if the cache was written
-      - run: |
-          test -f .pixi/env/bin/python
-        if: matrix.os != 'windows-latest'
-      - run: |
-          test -f .pixi/env/python.exe
-        if: matrix.os == 'windows-latest'
+  # test-cache1:
+  #   name: Test cache 1/2
+  #   timeout-minutes: 10
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [windows-latest, ubuntu-latest, macos-latest]
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: Move pixi files
+  #       run: mv test/default/* .
+  #     - uses: ./
+  #       with:
+  #         cache: true
+  #         cache-key: test-cache-${{ github.sha }}-${{ github.run_attempt }}-
+  #     # check the action logs to see if the cache was written
+  #     - run: |
+  #         test -f .pixi/env/bin/python
+  #       if: matrix.os != 'windows-latest'
+  #     - run: |
+  #         test -f .pixi/env/python.exe
+  #       if: matrix.os == 'windows-latest'
 
-  test-cache2:
-    name: Test cache 2/2
-    timeout-minutes: 10
-    needs: test-cache1
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [windows-latest, ubuntu-latest, macos-latest]
-    steps:
-      - uses: actions/checkout@v4
-      - name: Move pixi files
-        run: mv test/default/* .
-      - uses: ./
-        with:
-          cache: true
-          cache-key: test-cache-${{ github.sha }}-${{ github.run_attempt }}-
-      # check the action logs to see if the cache was restored
-      - run: |
-          test -f .pixi/env/bin/python
-        if: matrix.os != 'windows-latest'
-      - run: |
-          test -f .pixi/env/python.exe
-        if: matrix.os == 'windows-latest'
+  # test-cache2:
+  #   name: Test cache 2/2
+  #   timeout-minutes: 10
+  #   needs: test-cache1
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [windows-latest, ubuntu-latest, macos-latest]
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: Move pixi files
+  #       run: mv test/default/* .
+  #     - uses: ./
+  #       with:
+  #         cache: true
+  #         cache-key: test-cache-${{ github.sha }}-${{ github.run_attempt }}-
+  #     # check the action logs to see if the cache was restored
+  #     - run: |
+  #         test -f .pixi/env/bin/python
+  #       if: matrix.os != 'windows-latest'
+  #     - run: |
+  #         test -f .pixi/env/python.exe
+  #       if: matrix.os == 'windows-latest'
 
-  test-cache-no-write:
-    name: Test cache no write
-    timeout-minutes: 10
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [windows-latest, ubuntu-latest, macos-latest]
-    steps:
-      - uses: actions/checkout@v4
-      - name: Move pixi files
-        run: mv test/default/* .
-      - uses: ./
-        with:
-          cache: true
-          cache-write: false
-          cache-key: test-cache-${{ github.sha }}-${{ github.run_attempt }}-
-      # check the action logs to see if the cache write was skipped
+  # test-cache-no-write:
+  #   name: Test cache no write
+  #   timeout-minutes: 10
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [windows-latest, ubuntu-latest, macos-latest]
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: Move pixi files
+  #       run: mv test/default/* .
+  #     - uses: ./
+  #       with:
+  #         cache: true
+  #         cache-write: false
+  #         cache-key: test-cache-${{ github.sha }}-${{ github.run_attempt }}-
+  #     # check the action logs to see if the cache write was skipped
 
   # not properly testable
   # https://github.com/actions/runner/issues/2347
